version: "3.8"

services:
  tributary:
    build: .
    ports:
      - "8000:8000"

  redis:
    image: redis
    ports:
      - "6379:6379"

  post-request:
    build: .
    command: python test_file.py
    depends_on:
      - tributary 