version: "3.8"

services:
  tributary:
    build: .
    ports:
      - "8000:8000"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://tributary:8000/collect"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"

  post-request:
    build: .
    command: ["sh", "-c", "sleep 20 && python test_file.py"]
    depends_on:
      - tributary